-- Supabase uses PostgreSQL (not MySQL). Run this in Supabase → SQL Editor if you manage schema manually.

-- Daily rollups for analytics charts (monthly report)
create table if not exists public.attendance_daily (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees (id) on delete cascade,
  day date not null,
  status text not null,
  updated_at timestamptz default now(),
  unique (employee_id, day)
);

create index if not exists attendance_daily_day_idx on public.attendance_daily (day);
create index if not exists attendance_daily_employee_idx on public.attendance_daily (employee_id);

alter table public.employees add column if not exists phone text;

alter table public.admins add column if not exists phone text;

-- Optional: tighten RLS for production (anon key). Example — allow read/write only for authenticated users:
-- alter table public.attendance_daily enable row level security;
-- (Add policies matching your auth model.)
