-- Excused-absence requests: students submit; admins approve/deny from the dashboard.
-- Run in Supabase → SQL Editor after `001_attendance_daily_and_phone.sql`.

create table if not exists public.excuse_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees (id) on delete cascade,
  reason text not null default '',
  attachment_data_url text,
  attachment_filename text,
  status text not null default 'pending',
  created_at timestamptz default now(),
  resolved_at timestamptz,
  constraint excuse_requests_status_chk check (status in ('pending', 'approved', 'denied'))
);

create index if not exists excuse_requests_employee_idx on public.excuse_requests (employee_id);
create index if not exists excuse_requests_status_idx on public.excuse_requests (status);

-- Optional RLS (anon client, same pattern as the rest of this app):
-- alter table public.excuse_requests enable row level security;
-- create policy "excuse_select" on public.excuse_requests for select to anon using (true);
-- create policy "excuse_insert" on public.excuse_requests for insert to anon with check (true);
-- create policy "excuse_update" on public.excuse_requests for update to anon using (true) with check (true);
